[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

# color schemes
[[plugins]]
repo = 'raphamorim/lucario'
[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
    let g:NERDTreeShowHidden = 1
'''

[[plugins]]
repo = 'cohama/lexima.vim'
